---

- name: Clone dotfiles
  git: repo={{ dotfiles_path }} dest=/home/{{ username }}/dotfiles

- name: Symlink dotfiles to home
  file: 
    src: /home/{{ username }}/dotfiles/{{ item }}
    dest: /home/{{ username }}/{{ item }} 
    owner: "{{ username }}"
    group: "{{ username }}"
    state: link
  with_items: "{{ dotfiles }}"
