---

- name: Clone dotfiles
  git: repo={{ dotfiles_path }} dest=/home/{{ user.name }}/dotfiles

- name: Symlink dotfiles to home
  file: 
    src: /home/{{ user.name }}/dotfiles/{{ item }}
    dest: /home/{{ user.name }}/{{ item }} 
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: link
  with_items: "{{ dotfiles }}"
