---

- name: Install gnome-terminal
  apt: name=gnome-terminal state=present update_cache=yes
  tags:
    - gnome-terminal

- name: Install bash-completion
  apt: name=bash-completion state=present update_cache=yes

- name: Copy gnome.conf
  copy: src=gnome.conf dest=/tmp/ owner={{ username }} group={{ username }}
  tags:
    - gnome-terminal

# dbus-launch because there are no active sessions running for the created user, thus a bus has to be created
- name: Push gnome-terminal config
  shell: dbus-launch dconf load /org/gnome/terminal/ < /tmp/gnome.conf
  become: yes
  become_user: "{{ username }}"
  tags:
    - gnome-terminal

